import { Card, Grid, Typography } from "@mui/material";
import styled from "styled-components";
import styles from "./index.css";
import Head from "next/head";
import dynamic from "next/dynamic";
import axios from "axios";
import io from "socket.io-client";
import { useState, useEffect, useRef } from "react";

const MapComponent = dynamic(() => import("../components/Map"), {
  ssr: false,
});
const HomeWrapper = styled.div`
  ${styles}
`;

export default function Home({ data }) {
  const [lands, setLands] = useState(data);
  const [loading, setLoading] = useState(false);

  const fetchMap = async () => {
    try {
        const response = await axios.get("https://rental-api.lordsofthelands.io/api/getMap").catch((err) => {
        console.log(err);
          });
          console.log("called")
          setLands(response.data);
    } catch (err) {
        console.log(err)
    }
		
	}
  useEffect(() => {
    fetchMap();
    const interval = setInterval(() => {
      fetchMap();
    }, 15000);
    return () => clearInterval(interval);
  }, []);

  // fetchMap();
  return (
      <div>
      <Head>
        <title>LOL Map</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MapComponent lands={lands} loading={loading} />
    </div>
  );
}
