import { Card, Grid, Typography } from "@mui/material";
import Head from "next/head";
import Image from "next/image";
import styled from "styled-components";

import styles from "./index.css";

const HomeWrapper = styled.div`
  ${styles}
`;

export default function Home() {
  return (
    <HomeWrapper>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="main">
        <Typography variant="h1" className="title">
          <a href="https://lolmaps-kqcg4.ondigitalocean.app/map">Open Maps</a>
        </Typography>
      </main>
    </HomeWrapper>
  );
}
